//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Usuarios.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class seguridadEntities : DbContext
    {
        public seguridadEntities()
            : base("name=seguridadEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            Usuario = Set<Usuario>();
            Sesion = Set<Sesion>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Usuario> Usuario { get; set; }
        internal virtual DbSet<Sesion> Sesion { get; set; }
    }
}
