//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Usuarios.Entities
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Sesion
    {
        public int id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public long duration { get; set; }
        public System.DateTime initTime { get; set; }
        public int Usuario_id { get; set; }
    
        internal virtual Usuario Usuario { get; set; }
    }
}
